# distrochooser
# Copyright (C) 2014-2025 Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Welcome Page
# distrochooser::translation::en::Welcome!
# distrochooser::translation::key::welcome-page-title
[page.welcome-page]
can_be_marked = false
next_page = "version-page"
hide_text = true
hide_help = true
[widget.html.welcome-page-widget-name]
template = "welcomeHTML"
pages = ["welcome-page"]

# Version page

# distrochooser::translation::en::You can select a simplified questionaire edition, which removes some super technical questions
# distrochooser::translation::key::version-page-text
# distrochooser::translation::en::Questionaire edition
# distrochooser::translation::key::version-page-title
[page.version-page]
can_be_marked = false
next_page = "scenario-page"

[widget.version.version-page-widget-name]
pages = ["version-page"]

# Scenario page

# distrochooser::translation::en::Software: Use case
# distrochooser::translation::key::scenario-page-title
[page.scenario-page]
next_page = "pc-knowledge-page"
hide_help = true

[widget.selection.scenario-page-widget-name]
topic = "scenario"
pages = ["scenario-page"]

# PC knowledge page

# distrochooser::translation::en::Computer knowledge
# distrochooser::translation::key::pc-knowledge-page-title
[page.pc-knowledge-page]
next_page = "linux-knowledge-page"
hide_help = true

[widget.radio.pc-knowledge-page-widget-name]
topic = "pc-knowledge"
pages = ["pc-knowledge-page"]

# Linux knowledge page

# distrochooser::translation::en::Linux and you
# distrochooser::translation::key::linux-knowledge-page-title
[page.linux-knowledge-page]
next_page = "installation-page"
hide_help = true

[widget.radio.linux-knowledge-page-widget-name]
topic = "linux-knowledge"
pages = ["linux-knowledge-page"]


# Installation page

# distrochooser::translation::en::Installation: Presets
# distrochooser::translation::key::installation-page-title
[page.installation-page]
next_page = "personal-requirements-page"
hide_help = true

[widget.selection.installation-page-widget-name]
topic = "installation"
pages = ["installation-page"]


# Personal requirement page

# distrochooser::translation::en::Personal recommendation requirements
# distrochooser::translation::key::personal-requirements-page-text
# distrochooser::translation::en::Personal recommendation requirements
# distrochooser::translation::key::personal-requirements-page-title
[page.personal-requirements-page]
next_page = "help-page"
not_in_versions = ["simplified", "full"]

[widget.metafilter.personal-requirements-page]
structure = [
   [
      "number.distro_age.filter_number_gt",
      "checkbox.must_have_assignment.filter_must_have_assignments",
   ],
   [
      "checkbox.must_match_language.filter_must_match_language",
   ],
]
pages = ["personal-requirements-page"]

# help page

# distrochooser::translation::en::Source for help
# distrochooser::translation::key::help-page-title
[page.help-page]
next_page = "ux-page"
hide_help = true

[widget.selection.help-page-widget-name]
topic = "help"
pages = ["help-page"]

# UX Page

# distrochooser::translation::en::User experience
# distrochooser::translation::key::ux-page-title
[page.ux-page]
next_page = "pricing-page"
hide_help = true

# TODO:  The UX question should be a media selection
[widget.selection.ux-page-widget-name]
topic = "ux"
pages = ["ux-page"]

# Pricing page

# distrochooser::translation::en::Distributions: Price
# distrochooser::translation::key::pricing-page-title
[page.pricing-page]
next_page = "scope-page"
not_in_versions = ["simplified"]
hide_help = true

[widget.selection.pricing-page-widget-name]
topic = "pricing"
pages = ["pricing-page"]

# Scope

# distrochooser::translation::en::Distributions: Scope
# distrochooser::translation::key::scope-page-title
[page.scope-page]
hide_help = true
next_page = "ideology-page"

[widget.selection.scope-page-widget-name]
topic = "scope"
pages = ["scope-page"]

# Ideology

# distrochooser::translation::en::The (license) ideology of a Linux distribution is a contentious debate. There are Linux distributions using mostly "free-licenses", others also use "non-free" software.
# distrochooser::translation::key::ideology-page-text
# distrochooser::translation::en::Distributions: Ideology
# distrochooser::translation::key::ideology-page-title
[page.ideology-page]
next_page = "privacy-page"
not_in_versions = ["simplified"]

[widget.selection.ideology-page-widget-name]
topic = "ideology"
not_in_versions = ["simplified"]
pages = ["ideology-page"]

# Privacy

# distrochooser::translation::en::Distributions: Privacy
# distrochooser::translation::key::privacy-page-title
[page.privacy-page]
hide_help = true
next_page = "administration-page"

[widget.selection.privacy-page-widget-name]
topic = "privacy"
pages = ["privacy-page"]

# Administration 

# distrochooser::translation::en::Administration
# distrochooser::translation::key::administration-page-title
[page.administration-page]
next_page = "updates-page"
hide_help = true

[widget.selection.administration-page-widget-name]
topic = "administration"
pages = ["administration-page"]
not_in_versions = ["simplified"]

# Updates 

# distrochooser::translation::en::Software: Updates
# distrochooser::translation::key::updates-page-title
[page.updates-page]
next_page = "result-page"
hide_help = true
not_in_versions = ["simplified"]

[widget.selection.updates-page-widget-name]
topic = "updates"
pages = ["updates-page"]

# Results

# distrochooser::translation::en::Show your results
# distrochooser::translation::key::result-page-title
[page.result-page]
hide_help = true
hide_text = true
can_be_marked = false

[widget.share.result-page-widget-name]
topic = "result"
pages = ["result-page"]

[widget.feedback.result-page-feedback-widget]
topic = "result"
row = 2
pages = ["result-page"]

[widget.html.result-page-language-list]
template = "languageHTML"
row = 3
pages = ["result-page"]

[widget.result.result-page-widget-name]
row = 3
topic = "result"
pages = ["result-page"]

# Widgets present on all (or many) pages

[widget.navigation.global-nav]
row = 4
col = 1
pages = [
   "welcome-page",
   "version-page",
   "scenario-page",
   "pc-knowledge-page",
   "linux-knowledge-page",
   "installation-page",
   "personal-requirements-page",
   "help-page",
   "ux-page",
   "pricing-page",
   "scope-page",
   "ideology-page",
   "updates-page",
   "administration-page",
   "privacy-page",
]
